# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local socket connections inside the postgres container.
local   all             all                                     trust

# Docker compose network connections from the application and pgAdmin.
host    all             all             0.0.0.0/0               md5
host    all             all             ::/0                    md5
